### ISSUE TITLE
Crashing after ~5th Iteration (incomplete fetch)

### ISSUE THREAD

**Issue by james1236** [vaclavsvejcar/ytb-history-scraper#3]
Running Windows 10, whenever I do `run fetch` it gets to roughly the 5th iteration before crashing, failing to finish downloading the full history list which should be a few 10,000s long. 

Error message below (using latest ytb-history-downloader source)

```
sbt:ytb-history-downloader> run fetch
[info] Running com.github.vaclavsvejcar.yhd.Launcher fetch
-- Welcome to the Youtube History Downloader (YHD) --
Parsing Youtube cookies from 'cookies.txt'...
Iteration 1 - writing down initial list of videos (total 200)
Iteration 2 - writing down next 198 videos (total 398 videos)
Iteration 3 - writing down next 199 videos (total 597 videos)
Iteration 4 - writing down next 199 videos (total 796 videos)
Iteration 5 - writing down next 200 videos (total 996 videos)
[error] (run-main-2) java.util.NoSuchElementException
[error] java.util.NoSuchElementException
[error]         at java.util.ArrayList$Itr.next(ArrayList.java:854)
[error]         at scala.collection.convert.JavaCollectionWrappers$JIteratorWrapper.next(JavaCollectionWrappers.scala:39)
[error]         at scala.collection.Iterator$$anon$9.next(Iterator.scala:573)
[error]         at scala.collection.IterableOps.head(Iterable.scala:219)
[error]         at scala.collection.IterableOps.head$(Iterable.scala:219)
[error]         at net.ruippeixotog.scalascraper.model.LazyElementQuery.head(ElementQuery.scala:40)
[error]         at net.ruippeixotog.scalascraper.scraper.ContentExtractors$.net$ruippeixotog$scalascraper$scraper$ContentExtractors$$$anonfun$element$1(ContentExtractors.scala:19)
[error]         at net.ruippeixotog.scalascraper.scraper.ContentExtractors$$anonfun$1.extract(ContentExtractors.scala:19)
[error]         at net.ruippeixotog.scalascraper.scraper.ContentExtractors$$anonfun$1.extract(ContentExtractors.scala:19)
[error]         at net.ruippeixotog.scalascraper.scraper.HtmlExtractor.$anonfun$mapQuery$1(HtmlExtractor.scala:43)
[error]         at net.ruippeixotog.scalascraper.scraper.HtmlExtractor$$anon$1.extract(HtmlExtractor.scala:60)
[error]         at net.ruippeixotog.scalascraper.dsl.ScrapingOps$ElementsScrapingOps.$anonfun$extract$1(ScrapingOps.scala:15)
[error]         at scalaz.Monad.$anonfun$map$2(Monad.scala:14)
[error]         at scalaz.IdInstances$$anon$1.point(Id.scala:20)
[error]         at scalaz.Monad.$anonfun$map$1(Monad.scala:14)
[error]         at scalaz.IdInstances$$anon$1.bind(Id.scala:22)
[error]         at scalaz.Monad.map(Monad.scala:14)
[error]         at scalaz.Monad.map$(Monad.scala:14)
[error]         at scalaz.IdInstances$$anon$1.map(Id.scala:19)
[error]         at scalaz.syntax.FunctorOps.map(FunctorSyntax.scala:10)
[error]         at net.ruippeixotog.scalascraper.dsl.ScrapingOps$ElementsScrapingOps.extract(ScrapingOps.scala:15)
[error]         at net.ruippeixotog.scalascraper.dsl.ScrapingOps$ElementsScrapingOps.$greater$greater(ScrapingOps.scala:19)
[error]         at com.github.vaclavsvejcar.yhd.tools.Parsers$.$anonfun$parseVideoRefs$1(Parsers.scala:48)
[error]         at scala.collection.immutable.List.map(List.scala:223)
[error]         at com.github.vaclavsvejcar.yhd.tools.Parsers$.parseVideoRefs(Parsers.scala:44)
[error]         at com.github.vaclavsvejcar.yhd.downloader.HistoryDownloader.$anonfun$fetchNext$4(HistoryDownloader.scala:77)
[error]         at scala.Option.map(Option.scala:242)
[error]         at com.github.vaclavsvejcar.yhd.downloader.HistoryDownloader.fetchNext(HistoryDownloader.scala:77)
[error]         at com.github.vaclavsvejcar.yhd.downloader.HistoryDownloader.next$1(HistoryDownloader.scala:46)
[error]         at com.github.vaclavsvejcar.yhd.downloader.HistoryDownloader.$anonfun$fetchAndSave$1(HistoryDownloader.scala:64)
[error]         at com.github.vaclavsvejcar.yhd.downloader.HistoryDownloader.$anonfun$fetchAndSave$1$adapted(HistoryDownloader.scala:42)
[error]         at com.github.vaclavsvejcar.yhd.tools.Using$.apply(Using.scala:29)
[error]         at com.github.vaclavsvejcar.yhd.downloader.HistoryDownloader.fetchAndSave(HistoryDownloader.scala:42)
[error]         at com.github.vaclavsvejcar.yhd.Launcher$.$anonfun$new$1(Launcher.scala:24)
[error]         at com.github.vaclavsvejcar.yhd.Launcher$.$anonfun$new$1$adapted(Launcher.scala:17)
[error]         at scala.Option.foreach(Option.scala:437)
[error]         at com.github.vaclavsvejcar.yhd.Launcher$.delayedEndpoint$com$github$vaclavsvejcar$yhd$Launcher$1(Launcher.scala:17)
[error]         at com.github.vaclavsvejcar.yhd.Launcher$delayedInit$body.apply(Launcher.scala:12)
[error]         at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error]         at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error]         at scala.App.$anonfun$main$1(App.scala:73)
[error]         at scala.App.$anonfun$main$1$adapted(App.scala:73)
[error]         at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
[error]         at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:921)
[error]         at scala.App.main(App.scala:73)
[error]         at scala.App.main$(App.scala:71)
[error]         at com.github.vaclavsvejcar.yhd.Launcher$.main(Launcher.scala:12)
[error]         at com.github.vaclavsvejcar.yhd.Launcher.main(Launcher.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
[error] Total time: 15 s, completed XXX
sbt:ytb-history-downloader>
```

**Comment by vaclavsvejcar** [comment]
Thanks for reporting this issue. At first glance it looks like there might be some problem with parsing video time for some particular video for unknown reason (maybe deleted video or something like that?). Unfortunately I'm unable to reproduce this with my own YouTube history, but I'll try to rewrite the parsing logic to be more foolproof and ignore such possible differences, instead of crashing the entire app.

**Comment by vaclavsvejcar** [comment]
So I pushed a quick fix that should make the video details parser more robust and should prevent it from crashing when reading unexpected input. As a temporal solution, any video that cannot be parsed for any reason is excluded from resulting list and user is informed about this in console output. This is not ideal solution, but I need to investigate more how is it possible that such situation can even happen. Better way of error processing will be analyzed and implemented in some following task.

@james1236 Can you please pull the recent version and retest? Also if you have any chance to manually reach that video in your YouTube history that crashes the app, it would be super helpful as we could give this case into test and implement handling of such situation properly. Unfortunately, I'm not able to reproduce this.

**Comment by james1236** [comment]
Thank you for taking the time to fix these problems, you've been really helpful! I had a couple of videos skipped without it crashing so it seems to be working perfectly (106 Iterations, 20616 videos, 5 skipped). Just a suggestion, is it possible to get the amount of the video you have watched (shown by the red bar under the thumbnail in YouTube) & other data or does their API not support that? Would be useful for finding out your total watch time.

**Comment by james1236** [comment]
Also if you dump whatever info you get from the skipped videos to console I could help you find them

**Comment by vaclavsvejcar** [comment]
Glad to hear it works now :-) I plan to implement more informative debugging output in #6, so after this will be implemented, any help regarding figuring out what are these excluded videos will be welcomed.

Regarding the red bar (amout of video you have watched), it should be definitely possible to include in fetched data. I'm not using any official YouTube API because AFAIK there's no one that would allow to fetch entire watch history. Instead, I'm using scraping technique, where the app pretends to be regular web browser and simulates being user that scrolls down the history page :-) So everything you see on your history page can be fetched and included to the report by this tool.

BTW I have some plans with the report itself, I'd like to mainly improve the performance, but also add some features such as sorting (e.g. by most often watched videos, etc.) and better navigation (maybe some kind of pagination, search feature, ...).

**Comment by vaclavsvejcar** [comment]
@james1236 As part of #6 I added an option to produce more verbose output for debugging purposes. Can you please re-run the fetch step using `run fetch --debug` from SBT console and send me the output? It should contain both stack trace and HTML snippets of elements that failed to parse, it should help me to figure out what's happening there and adjust parsing for this case.

**Comment by james1236** [comment]
Thanks, it's when the program encounters a live stream in the history that is still going at the time of encountering it (such as the 24/7 nasa live stream and 24/7 radio live streams that caused my issue). If you open the links they're still valid since the live streams are still going.

Log below:

```
1 video(s) were skipped due to parsing errors (re-run with --debug for details) ParseError(Cannot parse field 'video duration',JsoupElement(&lt;div class=&quot;yt-lockup clearfix yt-lockup-video yt-lockup-tile vve-check&quot; data-context-item-id=&quot;21X5lGlDOfg&quot; data-visibility-tracking=XXX==&quot;&gt;
 &lt;div class=&quot;yt-lockup-dismissable&quot;&gt;
  &lt;div class=&quot;yt-lockup-thumbnail&quot;&gt;
   &lt;span class=&quot; spf-link ux-thumb-wrap contains-addto&quot;&gt;&lt;a href=&quot;/watch?v=21X5lGlDOfg&quot; class=&quot;yt-uix-sessionlink&quot; aria-hidden=&quot;true&quot; data-sessionlink=&quot;ei=XXXX&quot;&gt; &lt;span class=&quot;video-thumb yt-thumb yt-thumb-196&quot;&gt; &lt;span class=&quot;yt-thumb-default&quot;&gt; &lt;span class=&quot;yt-thumb-clip&quot;&gt; &lt;img src=XXX&quot; width=&quot;196&quot; data-thumb=&XXXmg=&quot;1&quot; alt=&quot;&quot; onload=&quot;;window.__ytRIL &amp;amp;&amp;amp; __ytRIL(this)&quot; aria-hidden=&quot;true&quot;&gt; &lt;span class=&quot;vertical-align&quot;&gt;&lt;/span&gt; &lt;/span&gt; &lt;/span&gt; &lt;/span&gt; &lt;/a&gt; &lt;span class=&quot;thumb-menu dark-overflow-action-menu video-actions&quot;&gt; &lt;/span&gt; &lt;button class=&quot;yt-uix-button yt-uix-button-size-small yt-uix-button-default yt-uix-button-empty yt-uix-button-has-icon no-icon-markup addto-button video-actions spf-nolink hide-until-delayloaded addto-watch-later-button yt-uix-tooltip&quot; type=&quot;button&quot; onclick=&quot;;return false;&quot; title=&quot;Watch Later&quot; role=&quot;button&quot; data-video-ids=&quot;21X5lGlDOfg&quot;&gt;&lt;/button&gt; &lt;/span&gt;
  &lt;/div&gt;
  &lt;div class=&quot;yt-lockup-content&quot;&gt;
   &lt;h3 class=&quot;yt-lockup-title contains-action-menu&quot;&gt;&lt;a class=&quot;yt-uix-sessionlink yt-uix-tile-link spf-link yt-ui-ellipsis yt-ui-ellipsis-2&quot; dir=&quot;ltr&quot; title=&quot;NASA Live: Official Stream of NASA TV&quot; data-sessionlink=&quotXXX&quot; href=&quot;/watch?v=21X5lGlDOfg&quot; rel=&quot;nofollow&quot;&gt;NASA Live: Official Stream of NASA TV&lt;/a&gt;&lt;/h3&gt;
   &lt;div class=&quot;yt-lockup-byline&quot;&gt;
    &lt;a XXXquot; class=&quot;yt-uix-sessionlink yt-user-name spf-link &quot; aria-label=&quot;Go to the user page for NASA
&quot; data-sessionXXXquot; dir=&quot;ltr&quot;&gt;NASA&lt;/a&gt;
    &lt;span data-tooltip-text=&quot;Verified&quot; aria-label=&quot;Verified&quot; class=&quot;yt-channel-title-icon-verified yt-uix-tooltip yt-sprite&quot;&gt;&lt;/span&gt;
   &lt;/div&gt;
   &lt;div class=&quot;yt-lockup-meta&quot;&gt;
    &lt;ul class=&quot;yt-lockup-meta-info&quot;&gt;
     &lt;li&gt;216 watching&lt;/li&gt;
    &lt;/ul&gt;
   &lt;/div&gt;
   &lt;div class=&quot;yt-lockup-description yt-ui-ellipsis yt-ui-ellipsis-2&quot; dir=&quot;ltr&quot;&gt;
     Direct from America's space program to YouTube, watch NASA TV live streaming here to get the latest from our exploration of the universe and learn how we discover our home planet.
    &lt;br&gt;
    &lt;br&gt;NASA TV airs a v...
   &lt;/div&gt;
   &lt;div class=&quot;yt-lockup-badges&quot;&gt;
    &lt;ul class=&quot;yt-badge-list &quot;&gt;
     &lt;li class=&quot;yt-badge-item&quot;&gt;&lt;span class=&quot;yt-badge yt-badge-live&quot;&gt;Live now&lt;/span&gt;&lt;/li&gt;
    &lt;/ul&gt;
   &lt;/div&gt;
   &lt;div class=&quot;yt-uix-menu-container yt-lockup-action-menu&quot;&gt;
    &lt;ul class=&quot;yt-uix-menu-top-level-button-container&quot;&gt;
     &lt;li class=&quot;yt-uix-menu-top-level-button&quot;&gt;
      &lt;div class=&quot;service-endpoint-action-container hid&quot;&gt;
       &lt;div class=&quot;service-endpoint-replace-enclosing-action-notification hid&quot;&gt;
        &lt;div class=&quot;replace-enclosing-action-message&quot;&gt;
         &lt;span aria-label=&quot;Video removed: NASA Live: Official Stream of NASA TV.&quot;&gt;All views of this video removed from history&lt;/span&gt;
        &lt;/div&gt;
       &lt;/div&gt;
      &lt;/div&gt; &lt;button class=&quot;yt-uix-button yt-uix-button-size-default yt-uix-button-opacity yt-uix-button-empty yt-uix-button-has-icon dismiss-menu-choice yt-uix-tooltip&quot; type=&quot;button&quot; onclick=&quot;;return false;&quot; title=&quot;Remove from Watch history&quot; data-feedback-token=XXXt; data-action=&quot;replace-enclosing-action&quot;&gt;&lt;span class=&quot;yt-uix-button-icon-wrapper&quot;&gt;&lt;span class=&quot;yt-uix-button-icon yt-uix-button-icon-dismissal yt-sprite&quot;&gt;&lt;/span&gt;&lt;/span&gt;&lt;/button&gt; &lt;/li&gt;
    &lt;/ul&gt;
   &lt;/div&gt;
  &lt;/div&gt;
 &lt;/div&gt;
 &lt;div class=&quot;yt-lockup-notifications-container hid&quot; style=&quot;height:110px&quot;&gt;&lt;/div&gt;
&lt;/div&gt;),None)
java.util.NoSuchElementException
        at java.util.ArrayList$Itr.next(ArrayList.java:854)
        at scala.collection.convert.JavaCollectionWrappers$JIteratorWrapper.next(JavaCollectionWrappers.scala:39)
        at scala.collection.Iterator$$anon$9.next(Iterator.scala:573)
        at scala.collection.IterableOps.head(Iterable.scala:219)
        at scala.collection.IterableOps.head$(Iterable.scala:219)
        at net.ruippeixotog.scalascraper.model.LazyElementQuery.head(ElementQuery.scala:40)
        at net.ruippeixotog.scalascraper.scraper.ContentExtractors$.net$ruippeixotog$scalascraper$scraper$ContentExtractors$$$anonfun$element$1(ContentExtractors.scala:19)
        at net.ruippeixotog.scalascraper.scraper.ContentExtractors$$anonfun$1.extract(ContentExtractors.scala:19)
        at net.ruippeixotog.scalascraper.scraper.HtmlExtractor.$anonfun$mapQuery$1(HtmlExtractor.scala:43)
        at net.ruippeixotog.scalascraper.scraper.HtmlExtractor$$anon$1.extract(HtmlExtractor.scala:60)
        at net.ruippeixotog.scalascraper.dsl.ScrapingOps$ElementsScrapingOps.$anonfun$extract$1(ScrapingOps.scala:15)
        at scalaz.Monad.$anonfun$map$2(Monad.scala:14)
        at scalaz.IdInstances$$anon$1.point(Id.scala:20)
        at scalaz.Monad.$anonfun$map$1(Monad.scala:14)
        at scalaz.IdInstances$$anon$1.bind(Id.scala:22)
        at scalaz.Monad.map(Monad.scala:14)
        at scalaz.Monad.map$(Monad.scala:14)
        at scalaz.IdInstances$$anon$1.map(Id.scala:19)
        at scalaz.syntax.FunctorOps.map(FunctorSyntax.scala:10)
        at net.ruippeixotog.scalascraper.dsl.ScrapingOps$ElementsScrapingOps.extract(ScrapingOps.scala:15)
        at net.ruippeixotog.scalascraper.dsl.ScrapingOps$ElementsScrapingOps.$greater$greater(ScrapingOps.scala:19)
        at com.github.vaclavsvejcar.yhd.parsers.VideoRefParser$.$anonfun$parseVideoRef$7(VideoRefParser.scala:26)
        at com.github.vaclavsvejcar.yhd.parsers.VideoRefParser$.$anonfun$extract$1(VideoRefParser.scala:34)
        at scala.util.Try$.apply(Try.scala:210)
        at com.github.vaclavsvejcar.yhd.parsers.VideoRefParser$.extract(VideoRefParser.scala:34)
        at com.github.vaclavsvejcar.yhd.parsers.VideoRefParser$.$anonfun$parseVideoRef$6(VideoRefParser.scala:25)
        at scala.util.Either.flatMap(Either.scala:352)
        at com.github.vaclavsvejcar.yhd.parsers.VideoRefParser$.$anonfun$parseVideoRef$4(VideoRefParser.scala:24)
        at scala.util.Either.flatMap(Either.scala:352)
        at com.github.vaclavsvejcar.yhd.parsers.VideoRefParser$.$anonfun$parseVideoRef$2(VideoRefParser.scala:23)
        at scala.util.Either.flatMap(Either.scala:352)
        at com.github.vaclavsvejcar.yhd.parsers.VideoRefParser$.parseVideoRef(VideoRefParser.scala:22)
        at com.github.vaclavsvejcar.yhd.parsers.VideoRefParser$.$anonfun$parseVideoRefs$1(VideoRefParser.scala:18)
        at scala.collection.immutable.List.map(List.scala:223)
        at com.github.vaclavsvejcar.yhd.parsers.VideoRefParser$.parseVideoRefs(VideoRefParser.scala:18)
        at com.github.vaclavsvejcar.yhd.downloader.HistoryDownloader.$anonfun$fetchNext$4(HistoryDownloader.scala:80)
        at scala.Option.map(Option.scala:242)
        at com.github.vaclavsvejcar.yhd.downloader.HistoryDownloader.fetchNext(HistoryDownloader.scala:80)
        at com.github.vaclavsvejcar.yhd.downloader.HistoryDownloader.next$1(HistoryDownloader.scala:48)
        at com.github.vaclavsvejcar.yhd.downloader.HistoryDownloader.$anonfun$fetchAndSave$1(HistoryDownloader.scala:67)
        at com.github.vaclavsvejcar.yhd.downloader.HistoryDownloader.$anonfun$fetchAndSave$1$adapted(HistoryDownloader.scala:44)
        at com.github.vaclavsvejcar.yhd.tools.Using$.apply(Using.scala:29)
        at com.github.vaclavsvejcar.yhd.downloader.HistoryDownloader.fetchAndSave(HistoryDownloader.scala:44)
        at com.github.vaclavsvejcar.yhd.Launcher$.$anonfun$new$1(Launcher.scala:33)
        at com.github.vaclavsvejcar.yhd.Launcher$.$anonfun$new$1$adapted(Launcher.scala:21)
        at scala.Option.foreach(Option.scala:437)
        at com.github.vaclavsvejcar.yhd.Launcher$.delayedEndpoint$com$github$vaclavsvejcar$yhd$Launcher$1(Launcher.scala:21)
        at com.github.vaclavsvejcar.yhd.Launcher$delayedInit$body.apply(Launcher.scala:15)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1(App.scala:73)
        at scala.App.$anonfun$main$1$adapted(App.scala:73)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:921)
        at scala.App.main(App.scala:73)
        at scala.App.main$(App.scala:71)
        at com.github.vaclavsvejcar.yhd.Launcher$.main(Launcher.scala:15)
        at com.github.vaclavsvejcar.yhd.Launcher.main(Launcher.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sbt.Run.invokeMain(Run.scala:98)
        at sbt.Run.run0(Run.scala:92)
        at sbt.Run.execute$1(Run.scala:68)
        at sbt.Run.$anonfun$run$4(Run.scala:80)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
        at sbt.TrapExit$App.run(TrapExit.scala:253)
```

**Comment by vaclavsvejcar** [comment]
Thanks a lot for the provided data, it makes sense now. I'm reopening the issue because we clearly don't want to drop these unfinished live streams from the history, but instead just omit the video time. I'll add this case to tests and to necessary changes in code.

**Comment by vaclavsvejcar** [comment]
@james1236 It should behave correctly now, I changed the logic so live stream videos are not excluded and are displayed in fetched history, just without the duration time. Thanks a lot for your help :-)

**Comment by james1236** [comment]
No problem :)
